apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.example.description: Postgres Database
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - image: postgres:9.4
        name: db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
