apiVersion: v1
kind: Service
metadata:
  annotations:
    com.example.description: Vote
    kompose.service.type: loadbalancer
  creationTimestamp: null
  labels:
    service: vote
  name: vote
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  selector:
    service: vote
  type: LoadBalancer
status:
  loadBalancer: {}
