apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: worker
    spec:
      containers:
      - image: docker/example-voting-app-worker:latest
        name: worker
        resources: {}
      restartPolicy: Always
status: {}
