apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.service.type: loadbalancer
  creationTimestamp: null
  name: result
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: result
    spec:
      containers:
      - image: tmadams333/example-voting-app-result:latest
        name: result
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
