apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: loadbalancer
  creationTimestamp: null
  labels:
    service: result
  name: result
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 80
  selector:
    service: result
  type: LoadBalancer
status:
  loadBalancer: {}
